project:
  type: website

website:
  title: "webr-checker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jmclawson/webr-checker

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



